#!/bin/bash

for changed_file in $(git diff --name-only HEAD master); do
    echo $changed_file
    if test -f "$changed_file"; then
        changed_files="$changed_files $changed_file"
    fi
done

bundle exec rubocop $changed_files
ret_code=$?

if [ $ret_code != 0 ]; then
    echo Rubocop returned $ret_code
    echo "Apply auto-fix? (y/n)"
    exec < /dev/tty
    read -r yesno
    if [[ $yesno == 'y' ]]; then
        rubocop -a $changed_files
        exit 1
    fi
    exit 1
fi

exit 0
